server:
  port: 8888
spring:
  cloud:
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-ser
          predicates :
            - Path=/pms/**
          filters:
            - Auth
        - id: wms-route
          uri: lb://wms-ser
          predicates:
            - Path=/wms/**
        - id: sms-route
          uri: lb://sms-ser
          predicates:
            - Path=/sms/**
        - id: oms-route
          uri: lb://oms-ser
          predicates:
            - Path=/oms/**
        - id: ums-route
          uri: lb://ums-ser
          predicates:
            - Path=/ums/**
        - id: index-route
          uri: lb://index-ser
          predicates:
            - Path=/api/index/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
        - id: order-route
          uri: lb://order-ser
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
            - Auth
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

jwt:
  token:
    pubKeyPath: E:\Code\Git\gmall\rsa.pub
    cookieName: gmall-token